### ISSUE TITLE
Option to specify host & path for route

### ISSUE THREAD

**Issue by LDL-GH** [IBM/ibm-licensing-operator#606]
Hi

We are currently installing the IBM Licensing Operator on openshift without a cloudpak.
Our instance looks as following:
```
apiVersion: operator.ibm.com/v1alpha1
kind: IBMLicensing
metadata:
  name: instance
spec:
  apiSecretToken: ibm-licensing-token
  datasource: datacollector
  httpsEnable: false
  routeEnabled: true
  routeOptions:
    tls:
      termination: edge
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
```

This works great and we get a route with termination edge, however I would like to be able to specify the host (and path) used for the route. This seems to be possible when defining an ingress using ingressOptions, but not for a route using routeOptions.

Could this be implemented?
